# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jmarqueti/proj_oop_3a/hardware_sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jmarqueti/proj_oop_3a/hardware_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jmarqueti/proj_oop_3a/hardware_sim/CMakeFiles /home/jmarqueti/proj_oop_3a/hardware_sim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jmarqueti/proj_oop_3a/hardware_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simulator

# Build rule for target.
simulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simulator
.PHONY : simulator

# fast build rule for target.
simulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/build
.PHONY : simulator/fast

#=============================================================================
# Target rules for targets named testCPU

# Build rule for target.
testCPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testCPU
.PHONY : testCPU

# fast build rule for target.
testCPU/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/build
.PHONY : testCPU/fast

#=============================================================================
# Target rules for targets named testDataValue

# Build rule for target.
testDataValue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testDataValue
.PHONY : testDataValue

# fast build rule for target.
testDataValue/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/build
.PHONY : testDataValue/fast

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/cpu.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/cpu.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/cpu.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/memory.o: src/memory.cpp.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/src/memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/simulator.o: src/simulator.cpp.o
.PHONY : src/simulator.o

# target to build an object file
src/simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.o
.PHONY : src/simulator.cpp.o

src/simulator.i: src/simulator.cpp.i
.PHONY : src/simulator.i

# target to preprocess a source file
src/simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.i
.PHONY : src/simulator.cpp.i

src/simulator.s: src/simulator.cpp.s
.PHONY : src/simulator.s

# target to generate assembly for a file
src/simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simulator.dir/build.make CMakeFiles/simulator.dir/src/simulator.cpp.s
.PHONY : src/simulator.cpp.s

tests/testCPU.o: tests/testCPU.cpp.o
.PHONY : tests/testCPU.o

# target to build an object file
tests/testCPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/tests/testCPU.cpp.o
.PHONY : tests/testCPU.cpp.o

tests/testCPU.i: tests/testCPU.cpp.i
.PHONY : tests/testCPU.i

# target to preprocess a source file
tests/testCPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/tests/testCPU.cpp.i
.PHONY : tests/testCPU.cpp.i

tests/testCPU.s: tests/testCPU.cpp.s
.PHONY : tests/testCPU.s

# target to generate assembly for a file
tests/testCPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testCPU.dir/build.make CMakeFiles/testCPU.dir/tests/testCPU.cpp.s
.PHONY : tests/testCPU.cpp.s

tests/testDataValue.o: tests/testDataValue.cpp.o
.PHONY : tests/testDataValue.o

# target to build an object file
tests/testDataValue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/tests/testDataValue.cpp.o
.PHONY : tests/testDataValue.cpp.o

tests/testDataValue.i: tests/testDataValue.cpp.i
.PHONY : tests/testDataValue.i

# target to preprocess a source file
tests/testDataValue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/tests/testDataValue.cpp.i
.PHONY : tests/testDataValue.cpp.i

tests/testDataValue.s: tests/testDataValue.cpp.s
.PHONY : tests/testDataValue.s

# target to generate assembly for a file
tests/testDataValue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testDataValue.dir/build.make CMakeFiles/testDataValue.dir/tests/testDataValue.cpp.s
.PHONY : tests/testDataValue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... simulator"
	@echo "... testCPU"
	@echo "... testDataValue"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/simulator.o"
	@echo "... src/simulator.i"
	@echo "... src/simulator.s"
	@echo "... tests/testCPU.o"
	@echo "... tests/testCPU.i"
	@echo "... tests/testCPU.s"
	@echo "... tests/testDataValue.o"
	@echo "... tests/testDataValue.i"
	@echo "... tests/testDataValue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

